apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - static-files
resources:
  - helmrelease.yaml
images:
  - name: kedark0kil/task-fluxcd
    newName: kedark0kil/task-fluxcd
    newTag: "0.1"